/* On Stride — anglais. Clé = texte français tel qu'il est écrit dans le code ; valeur = traduction.
   {n} remplace un nombre, {q} un nom entre « », {0} {1} des valeurs passées par le code.
   Pour ajouter une langue : copier ce fichier, traduire les valeurs, l'ajouter dans index.html et dans I18N.langs (js/i18n.js). */
'use strict';
I18N.add('en',{
/* --- mots identiques dans les deux langues --- */
'On Stride':'On Stride','Inbox':'Inbox','Kanban':'Kanban','Table':'Table','Notes':'Notes','Clients':'Clients','Client':'Client',
'Brief':'Brief','Prospect':'Lead','Cyan':'Cyan','Orange':'Orange','Total':'Total','Description':'Description','Checklist':'Checklist',
'Labels':'Labels','Menu':'Menu','Navigation':'Navigation','Agenda':'Agenda','Actions':'Actions','Cobalt':'Cobalt',
'Google':'Google','Discord':'Discord','GitHub':'GitHub','Apple':'Apple','Microsoft':'Microsoft','GitLab':'GitLab','Twitch':'Twitch',
'Français':'Français','English':'English','config.js':'config.js','LISEZ-MOI.md':'LISEZ-MOI.md',
'@undo':'Undo','Maj':'Shift','Échap':'Esc','puis':'then',

/* --- colonnes, modèles, statuts --- */
'À faire':'To do','En cours':'In progress','Terminé':'Done','Projet client':'Client project','Validation client':'Client review','Livré':'Delivered',
'Suivi de prospects':'Sales pipeline','Contacté':'Contacted','Devis envoyé':'Quote sent','Négociation':'Negotiation','Gagné':'Won',
'Contenu':'Content','Idées':'Ideas','Rédaction':'Writing','Relecture':'Review','Publié':'Published','Perso':'Personal',
'En attente':'On hold','Archivé':'Archived','Actif':'Active','En pause':'Paused',
'Aucune':'None','Basse':'Low','Moyenne':'Medium','Haute':'High',
'Bleu':'Blue','Rose':'Pink','Vert':'Green','Violet':'Purple','Émeraude':'Emerald','Corail':'Coral','Ardoise':'Slate',
'Liste':'List','Calendrier':'Calendar',
'lun.':'Mon','mar.':'Tue','mer.':'Wed','jeu.':'Thu','ven.':'Fri','sam.':'Sat','dim.':'Sun',

/* --- navigation --- */
'Accueil':'Home','Mes tâches':'My tasks','Projets':'Projects','Réglages':'Settings','Tâches':'Tasks','Tâche':'Task',
'Réduire le menu':'Collapse the menu','Réduire le menu (Ctrl B)':'Collapse the menu (Ctrl B)','Agrandir le menu':'Expand the menu',
'Afficher ou masquer le menu':'Show or hide the menu','Menu (Ctrl B)':'Menu (Ctrl B)','Navigation principale':'Main navigation',
'Rechercher':'Search','Rechercher (Ctrl K)':'Search (Ctrl K)','Favoris':'Favourites','Espaces':'Spaces',
'Nouvel espace':'New space','Nom de l’espace':'Space name','Nom de l’espace, puis Entrée':'Space name, then Enter',
'Déplier ou replier':'Expand or collapse','Nouveau projet dans':'New project in','Nouveau projet':'New project',
'Options de l’espace':'Space options','Renommer':'Rename','Confirmer la suppression':'Confirm deletion','Supprimer l’espace':'Delete the space',
'Nom du projet':'Project name','Nom du projet, puis Entrée':'Project name, then Enter',
'Aucun projet. Ajoute-en avec le +':'No projects. Add one with the +','Aucun projet':'No projects',
'Mes projets':'My projects','Partagés avec moi':'Shared with me','Retour':'Back','Fil d’Ariane':'Breadcrumb',
'Éditeur':'Editor','Lecteur':'Viewer','Lecture seule':'Read only','Nouvelle tâche (N)':'New task (N)','Créer':'Create',
'Hors ligne':'Offline','Enregistrement…':'Saving…','Enregistré':'Saved','Chargement':'Loading','Annuler':'Cancel',

/* --- accueil --- */
'Aujourd’hui':'Today','Cette semaine':'This week','Projets récents':'Recent projects','Progression':'Progress',
'Activité récente':'Recent activity','Notes rapides':'Quick notes',
'à l’instant':'just now','il y a {n} min':'{n} min ago','il y a {n} h':'{n} h ago','il y a {n} j':'{n} d ago',
'Rien pour aujourd’hui':'Nothing for today','Aucune échéance aujourd’hui ni en retard.':'Nothing due today and nothing overdue.',
'Semaine dégagée':'A clear week','Aucune échéance dans les 7 prochains jours.':'Nothing due in the next 7 days.',
'Aucun projet pour le moment':'No projects yet','Crée ton premier projet pour commencer à organiser ton travail.':'Create your first project to start organising your work.',
'Créer un projet':'Create a project','cartes terminées sur {n}':'cards done out of {n}','carte terminée sur {n}':'card done out of {n}',
'Pas encore d’activité':'No activity yet','Les déplacements et changements de tes cartes apparaîtront ici.':'Moves and changes to your cards will show up here.',
'Aucun client actif':'No active clients','Ajoute un client pour suivre ses projets et ce qu’il te doit.':'Add a client to track their projects and what they owe you.',
'Ouvrir les clients':'Open clients','Reste à encaisser :':'Still to collect:','Reste à encaisser':'Still to collect',
'Une idée, un numéro, un pense-bête… Visible par toi seul.':'An idea, a number, a reminder… Only you can see this.',
'{n} projets':'{n} projects','{n} projet':'{n} project',
'Bonjour':'Good morning','Bonsoir':'Good evening','Bonjour,':'Good morning,','Bonsoir,':'Good evening,',
'{0} tâches pour aujourd’hui':'{0} tasks for today','{0} tâche pour aujourd’hui':'{0} task for today','{0} en retard':'{0} overdue','{0} cette semaine':'{0} this week',
'Rien d’urgent : aucune échéance proche.':'Nothing urgent: no deadlines coming up.','Ton espace est prêt.':'Your workspace is ready.',
'Nouvelle tâche':'New task','Terminer':'Done','Personnaliser':'Customise',
'Ce sont des exemples.':'These are examples.','Ils montrent ce que l’appli sait faire. Supprime-les quand tu veux.':'They show what the app can do. Delete them whenever you like.',
'Confirmer':'Confirm','Supprimer les exemples':'Delete the examples',
'Bienvenue dans On Stride':'Welcome to On Stride','Trois étapes pour être chez toi.':'Three steps to make it yours.',
'Dis-moi ton prénom':'Tell me your first name','Ton prénom':'Your first name','Crée ton premier projet':'Create your first project',
'Ajoute une première tâche':'Add a first task','Ajouter':'Add','Masquer':'Hide',
'Projets actifs':'Active projects','En retard':'Overdue','Terminées':'Done','Clients actifs':'Active clients',
'Rien à afficher pour l’instant':'Nothing to show yet','Les projets partagés apparaîtront ici.':'Shared projects will show up here.',
'Monter':'Move up','Descendre':'Move down','Masquer ce bloc':'Hide this block','Blocs masqués :':'Hidden blocks:',
'Glisse les blocs ou utilise les flèches pour les réorganiser. La disposition est mémorisée.':'Drag the blocks or use the arrows to rearrange them. The layout is remembered.',

/* --- inbox, mes tâches --- */
'Ranger dans…':'File into…','Note tout de suite, range plus tard. Visible par toi seul.':'Jot it down now, file it later. Only you can see this.',
'Ajouter rapidement':'Quick add','Ajouter rapidement… ex. « Envoyer le devis demain priorité haute »':'Quick add… e.g. “Send the quote tomorrow high priority”',
'Ranger dans un projet':'File into a project','Supprimer':'Delete','Inbox à zéro':'Inbox zero',
'Écris une tâche ci-dessus sans choisir de projet. Tu la rangeras plus tard.':'Type a task above without picking a project. You can file it later.',
'Rappels':'Reminders','Traitées':'Processed','Vider':'Clear',
'Priorité haute':'High priority','Priorité moyenne':'Medium priority','Priorité basse':'Low priority','Sans échéance':'No due date','Plus tard':'Later',
'Les tâches qui te sont assignées ou sans responsable.':'Tasks assigned to you or to no one.','Toutes tes tâches, tous projets confondus.':'All your tasks, across every project.',
'Affichage':'View','Filtres':'Filters','Filtre':'Filter','Aucune tâche terminée':'No completed tasks','Les tâches que tu termines apparaîtront ici.':'Tasks you complete will show up here.',
'Rien dans ce filtre':'Nothing in this filter','Change de filtre, ou ajoute une tâche.':'Switch filter, or add a task.',

/* --- calendrier --- */
'Mois précédent':'Previous month','Mois suivant':'Next month','Aucune échéance ce mois-ci':'Nothing due this month',
'Donne une échéance à une tâche pour la voir ici.':'Give a task a due date to see it here.','Ajouter une tâche':'Add a task','Ajouter une tâche le {n}':'Add a task on the {n}',
'{n} tâche sans échéance n’apparaît pas ici.':'{n} task without a due date isn’t shown here.','{n} tâches sans échéance n’apparaissent pas ici.':'{n} tasks without a due date aren’t shown here.',
'Tous les projets':'All projects','Toutes les échéances.':'Every due date.','Toutes les échéances. Glisse une tâche sur un autre jour pour la déplacer.':'Every due date. Drag a task onto another day to move it.',
'Filtrer par projet':'Filter by project','Mois':'Month',

/* --- projets --- */
'Actifs':'Active','Archivés':'Archived','{n} projets, rangés par espace.':'{n} projects, grouped by space.','{n} projet, rangés par espace.':'{n} project, grouped by space.',
'Nouveau projet (nom, puis Entrée)':'New project (name, then Enter)','Aucun favori':'No favourites',
'Ouvre un projet et clique sur l’étoile pour le retrouver ici et dans le menu.':'Open a project and click the star to find it here and in the menu.',
'Aucun projet archivé':'No archived projects','Passe le statut d’un projet sur « Archivé » pour le ranger ici.':'Set a project’s status to “Archived” to put it away here.',

/* --- clients --- */
'Ton carnet de clients. Visible par toi seul, même quand tu partages un projet.':'Your client book. Only you can see it, even when you share a project.',
'Nom du client':'Client name','Nouveau client (nom, puis Entrée)':'New client (name, then Enter)','Aucun client pour l’instant':'No clients yet',
'Ajoute un client pour suivre ses projets, ses coordonnées et ce qu’il te doit.':'Add a client to track their projects, contact details and what they owe you.',
'Statut':'Status','Avancement':'Progress','Montant':'Amount','Encaissé':'Received','Reste':'Outstanding','Vide':'Empty',
'Société':'Company','E-mail':'Email','Téléphone':'Phone','Montant total':'Total amount',
'Besoins, tarifs convenus, interlocuteurs, historique…':'Needs, agreed rates, contacts, history…','Projets de ce client':'This client’s projects',
'Nouveau projet pour ce client':'New project for this client',
'Aucun projet relié. Crée-en un ci-dessus, ou choisis ce client dans les détails d’un projet.':'No linked projects. Create one above, or pick this client in a project’s details.',
'Supprimer ce client ? Ses projets sont conservés.':'Delete this client? Their projects are kept.','Supprimer le client':'Delete the client',

/* --- page de projet --- */
'Partir d’un modèle de colonnes ?':'Start from a column template?','Sinon, garde les trois colonnes ci-dessous et renomme-les.':'Otherwise, keep the three columns below and rename them.',
'Nom de la colonne':'Column name','Options de la colonne':'Column options','Déplacer à gauche':'Move left','Déplacer à droite':'Move right',
'Ne plus compter comme terminée':'Stop counting as done','Compter comme terminée':'Count as done','Supprimer la colonne':'Delete the column',
'Titre de la carte':'Card title','Titre de la carte…':'Card title…','Fermer':'Close','Fermer (Échap)':'Close (Esc)','Ajouter une carte':'Add a card',
'+ Ajouter une colonne':'+ Add a column','Nouvelle colonne':'New column','Nouvelle carte':'New card','Ajouter une carte, puis Entrée':'Add a card, then Enter',
'Aucune carte ne correspond':'No matching cards','Change le filtre pour les voir.':'Change the filter to see them.','Aucune carte pour l’instant':'No cards yet',
'Écris la première dans le champ ci-dessus.':'Type the first one in the field above.','Les cartes de ce projet apparaîtront ici.':'This project’s cards will show up here.',
'Carte':'Card','Colonne':'Column','Priorité':'Priority','Assigné':'Assignee','Échéance':'Due date','Aucune carte à afficher.':'No cards to show.',
'Notes du projet':'Project notes','Notes du projet : brief, comptes rendus, liens utiles, décisions…':'Project notes: brief, meeting notes, useful links, decisions…',
'Ces notes sont visibles par les personnes avec qui tu partages ce projet. Pour des notes confidentielles, utilise le bloc « Privé » dans les détails.':'These notes are visible to the people you share this project with. For confidential notes, use the “Private” block in the details.',
'Pas de notes':'No notes','Ce projet n’a pas encore de notes.':'This project has no notes yet.','Filtrer les cartes':'Filter cards',
'Lecteur · voit tout, ne modifie rien':'Viewer · sees everything, changes nothing','Éditeur · peut modifier les cartes':'Editor · can edit cards',
'Partage du projet':'Project sharing','Toi':'You','(toi)':'(you)','Propriétaire':'Owner','Rôle de':'Role of','Rôle':'Role',
'Retirer l’accès de':'Remove access for','Retirer l’accès':'Remove access','Partager avec ton client':'Share with your client',
'En lecteur':'As viewer','En éditeur':'As editor','adresse@exemple.com':'name@example.com','Adresse e-mail à inviter':'Email address to invite','Inviter':'Invite',
'La personne se connecte au site avec cette adresse (Google, Discord ou lien par e-mail) et retrouve le projet dans « Partagés avec moi ». Aucun e-mail n’est envoyé automatiquement : envoie-lui le lien. Tes clients, tes montants et tes notes privées ne lui sont jamais montrés.':'The person signs in to the site with this address (Google, Discord or email link) and finds the project under “Shared with me”. No email is sent automatically: send them the link. Your clients, amounts and private notes are never shown to them.',
'Copier le lien du projet':'Copy the project link','Changer l’icône':'Change the icon','Utiliser la pastille de couleur':'Use the colour dot',
'Retirer des favoris':'Remove from favourites','Ajouter aux favoris':'Add to favourites','Favori':'Favourite',
'Ajoute une description (objectif, contexte…)':'Add a description (goal, context…)','Partagé · {n}':'Shared · {n}','Privé':'Private',
'Tu es éditeur':'You’re an editor','Tu es lecteur':'You’re a viewer','Partager':'Share','Détails':'Details','Début':'Start','Vue par défaut':'Default view',
'Couleur':'Colour','Couleur du projet':'Project colour','Aucun':'None','Privé · visible par toi seul':'Private · only you can see this',
'Montant (€)':'Amount (€)','Encaissé (€)':'Received (€)','Notes privées':'Private notes',
'Notes privées : tarif, conditions, contacts, tout ce qui ne se partage pas.':'Private notes: rate, terms, contacts, anything you don’t share.',
'Supprimer ce projet et ses {n} cartes ?':'Delete this project and its {n} cards?','Supprimer ce projet et ses {n} carte ?':'Delete this project and its {n} card?','Supprimer le projet':'Delete the project',
'Terminée':'Done','Pas terminée':'Not done','Remettre à faire':'Mark as not done','Marquer comme terminée':'Mark as done',
'Passer dans « {0} »':'Move to “{0}”','{n} % terminé':'{n}% done','Commentaires':'Comments',

/* --- réglages --- */
'L’apparence est mémorisée sur cet appareil.':'Appearance and language are remembered on this device.','Compte':'Account','Mon compte':'My account','Se déconnecter':'Sign out',
'Profil':'Profile','Pour le message d’accueil et « Mes tâches ».':'For the greeting and “My tasks”.',
'Apparence et langue':'Appearance and language','Apparence':'Appearance','Langue':'Language','Thème':'Theme','Système':'System','Clair':'Light','Sombre':'Dark',
'Couleur d’accent':'Accent colour','Densité':'Density','Compacte':'Compact','Normale':'Normal','Confortable':'Comfortable',
'Taille du texte':'Text size','Petite':'Small','Grande':'Large','Tableau de bord':'Dashboard',
'Choisis les blocs affichés sur l’accueil. Pour les réorganiser, utilise « Personnaliser » sur l’accueil.':'Choose which blocks appear on the home page. To rearrange them, use “Customise” on the home page.',
'Partage':'Sharing','Chaque projet se partage séparément : ouvre un projet, puis « Partager ». Tu choisis pour chaque personne « Lecteur » ou « Éditeur ». Ton Inbox, tes clients, tes montants et tes notes privées restent visibles par toi seul.':'Each project is shared separately: open a project, then “Share”. For each person you choose “Viewer” or “Editor”. Your Inbox, clients, amounts and private notes stay visible to you only.',
'Données':'Data','Télécharge une copie de tout ton espace (projets, tâches, clients) dans un fichier.':'Download a copy of your whole workspace (projects, tasks, clients) as a file.',
'Exporter en JSON':'Export as JSON','Rechercher et lancer une commande':'Search and run a command','Raccourcis clavier':'Keyboard shortcuts',

/* --- connexion --- */
'L’espace de travail simple pour organiser tes projets, tes clients et ton travail.':'The simple workspace for organising your projects, your clients and your work.',
'Le site n’est pas encore relié à sa base de données.':'The site isn’t connected to its database yet.','Ouvre le fichier':'Open the file',
'et colle l’adresse de ton projet Supabase et sa clé « publishable », puis remets le site en ligne. Le guide':'and paste your Supabase project URL and its “publishable” key, then publish the site again. The guide',
'détaille chaque étape.':'covers every step.','Regarde ta boîte mail':'Check your inbox',
'Un lien de connexion vient d’être envoyé à':'A sign-in link has just been sent to','. Ouvre-le sur cet appareil.':'. Open it on this device.',
'Utiliser une autre adresse':'Use another address','Continuer avec':'Continue with','ou':'or','toi@exemple.com':'you@example.com','Adresse e-mail':'Email address',
'Envoi…':'Sending…','Recevoir un lien de connexion':'Email me a sign-in link',
'Un projet partagé avec toi ? Connecte-toi avec l’adresse e-mail qui a été invitée.':'Has a project been shared with you? Sign in with the email address that was invited.',
'Connexion impossible pour le moment.':'Can’t sign in right now.','Entre une adresse e-mail valide.':'Enter a valid email address.','Envoi impossible pour le moment.':'Can’t send right now.',

/* --- panneau de tâche --- */
'Dupliquer':'Duplicate','Titre':'Title','Inbox (pas encore rangée)':'Inbox (not filed yet)','Projet':'Project','Assigné à':'Assigned to','Personne':'Person',
'Supprimer le label':'Delete the label','Gérer':'Manage','+ Créer un label':'+ Create a label','Nom du label':'Label name','Couleur du label':'Label colour',
'Détails, liens, idées…':'Details, links, ideas…','Pas de description.':'No description.','Décocher':'Uncheck','Cocher':'Check',
'Élément de checklist':'Checklist item','Supprimer l’élément':'Delete the item','Ajouter un élément, puis Entrée':'Add an item, then Enter','Nouvel élément':'New item',
'Supprimer le commentaire':'Delete the comment','Écrire un commentaire, puis Entrée':'Write a comment, then Enter','Nouveau commentaire':'New comment','Activité':'Activity',

/* --- palette, ajout rapide, menus --- */
'Notes de « {q} »':'Notes of “{q}”','Récents':'Recent','Nouveau client':'New client','Aller à':'Go to','Vue du projet':'Project view',
'Vue Kanban':'Kanban view','Vue Liste':'List view','Vue Table':'Table view','Vue Calendrier':'Calendar view','Vue Notes':'Notes view',
'Thème clair':'Light theme','Thème sombre':'Dark theme','Thème du système':'System theme','Créer la tâche « {q} »':'Create the task “{q}”',
'Aucun résultat':'No results','Essaie un autre mot.':'Try another word.','Palette de commandes':'Command palette',
'Rechercher ou lancer une commande':'Search or run a command','Rechercher un projet, une tâche, une commande…':'Search for a project, a task, a command…',
'naviguer':'navigate','ouvrir':'open','fermer':'close',
'Titre de la tâche':'Task title','Corriger le responsive demain priorité haute':'Fix the mobile layout tomorrow high priority',
'Écris naturellement : « demain », « vendredi », « 12/11 », « dans 3 jours », « priorité haute », « #nomduprojet ».':'Write naturally: “tomorrow”, “friday”, “12/11” (day/month), “in 3 days”, “high priority”, “#projectname”.',
'Ouvrir':'Open','Déplacer vers':'Move to',

/* --- tutoriel --- */
'Bienvenue dans On Stride':'Welcome to On Stride',
'On Stride sert à ranger ton travail en projets, à suivre tes tâches et à montrer où tu en es à tes clients ou à tes potes. Je te montre l’essentiel en une minute.':'On Stride helps you organise your work into projects, keep track of your tasks and show your clients or friends where you’re at. Here’s the essentials in one minute.',
'Le menu':'The menu','Tout part d’ici. Accueil : la vue d’ensemble. Mes tâches : ce que tu as à faire. Projets : ton travail, bien rangé.':'Everything starts here. Home: the big picture. My tasks: what you have to do. Projects: your work, neatly organised.',
'Tes projets':'Your projects','Un projet, c’est un client, un site, une idée… Écris son nom ici puis appuie sur Entrée pour le créer. Dedans, chaque tâche est une carte que tu fais avancer : À faire, En cours, Terminé.':'A project is a client, a website, an idea… Type its name here and press Enter to create it. Inside, each task is a card you move forward: To do, In progress, Done.',
'Partager un projet':'Share a project','Dans un projet, le bouton « Partager » invite quelqu’un avec son adresse e-mail. En lecteur, il regarde ton avancée. En éditeur, il peut aussi modifier les cartes.':'In a project, the “Share” button invites someone by email address. As a viewer, they follow your progress. As an editor, they can also change the cards.',
'Ce bouton note une tâche en deux secondes, depuis n’importe quelle page. Tu peux écrire « demain » ou « priorité haute » : l’appli comprend toute seule.':'This button captures a task in two seconds, from any page. You can type “tomorrow” or “high priority”: the app works it out.',
'L’Inbox':'The Inbox','Une tâche sans projet arrive dans l’Inbox. Tu notes vite sur le moment, tu ranges dans un projet plus tard.':'A task with no project lands in the Inbox. Jot it down now, file it into a project later.',
'Ton accueil':'Your home page','L’accueil résume tout : ce qui est prévu aujourd’hui, ce qui est en retard et où en sont tes projets. Touche un chiffre pour voir le détail.':'The home page sums it all up: what’s due today, what’s overdue and how your projects are going. Tap a number to see the details.',
'C’est parti !':'Off you go!','Le mieux pour commencer : créer ton premier projet. Tu peux revoir ce tutoriel quand tu veux dans Réglages.':'The best way to start: create your first project. You can replay this tutorial any time in Settings.',
'Passer le tutoriel':'Skip the tutorial','Précédent':'Back','Suivant':'Next','Commencer':'Start','Créer mon premier projet':'Create my first project',
'Tutoriel':'Tutorial','Une visite guidée de l’appli en une minute : le menu, les projets, le partage, les tâches.':'A one-minute guided tour of the app: the menu, projects, sharing, tasks.',
'Revoir le tutoriel':'Replay the tutorial','Aide':'Help','Tu peux revoir le tutoriel dans Réglages.':'You can replay the tutorial in Settings.',

/* --- photos --- */
'Photos':'Photos','Photo':'Photo','Photo {n}':'Photo {n}','Agrandir la photo {n}':'Enlarge photo {n}','Supprimer la photo {n}':'Delete photo {n}','Envoi de la photo…':'Uploading the photo…',
'Ajouter des photos':'Add photos','Photo précédente':'Previous photo','Photo suivante':'Next photo',
'Choisis une image : photo, capture d’écran…':'Pick an image: a photo, a screenshot…','Maximum {0} photos par tâche.':'Maximum {0} photos per task.',
'Maximum {0} photos par tâche : les suivantes n’ont pas été ajoutées.':'Maximum {0} photos per task: the rest weren’t added.',
'Les photos ne sont pas encore activées : relance le fichier supabase/schema.sql dans Supabase.':'Photos aren’t enabled yet: run the file supabase/schema.sql again in Supabase.',
'Envoi de la photo impossible. Réessaie dans un instant.':'Couldn’t upload the photo. Try again in a moment.','Cette image ne peut pas être lue.':'This image can’t be read.',
'Photo supprimée.':'Photo deleted.','Photo ajoutée':'Photo added','Photos ajoutées':'Photos added',

/* --- mot de passe --- */
'Façon de se connecter':'How to sign in','Lien par e-mail':'Email link','Mot de passe':'Password','Ton mot de passe':'Your password','8 caractères ou plus':'8 characters or more',
'Connexion…':'Signing in…','Créer mon compte':'Create my account','Se connecter':'Sign in',
'Tu reçois un seul e-mail pour confirmer ton adresse. Ensuite, ton mot de passe suffit.':'You get a single email to confirm your address. After that, your password is enough.',
'Déjà un compte ?':'Already have an account?','Première fois ici ?':'First time here?',
'Jamais choisi de mot de passe, ou oublié ? Passe par « Lien par e-mail », puis choisis-en un dans Réglages.':'Never set a password, or forgot it? Use “Email link”, then set one in Settings.',
'Tu reçois un lien par e-mail. Une fois connecté, tu peux choisir un mot de passe dans Réglages pour ne plus attendre d’e-mail.':'You get a link by email. Once signed in, you can set a password in Settings so you never wait for an email again.',
'Un e-mail de confirmation vient d’être envoyé à':'A confirmation email has just been sent to','. Clique sur le lien dedans : c’est la seule fois, ensuite ton mot de passe suffit.':'. Click the link inside: it’s the only time, after that your password is enough.',
'Trop d’e-mails envoyés pour le moment. Attends un peu (jusqu’à une heure), ou connecte-toi avec ton mot de passe.':'Too many emails sent for now. Wait a while (up to an hour), or sign in with your password.',
'Adresse ou mot de passe incorrect. Si tu n’as jamais choisi de mot de passe, utilise « Lien par e-mail ».':'Wrong address or password. If you never set a password, use “Email link”.',
'Ton adresse n’est pas encore confirmée : clique sur le lien reçu par e-mail.':'Your address isn’t confirmed yet: click the link you received by email.',
'Mot de passe trop court : 8 caractères au minimum.':'Password too short: 8 characters minimum.','C’est déjà ton mot de passe actuel.':'That’s already your current password.',
'Ce lien de connexion a expiré ou a déjà servi. Demandes-en un nouveau.':'This sign-in link has expired or was already used. Ask for a new one.','Écris ton mot de passe.':'Type your password.',
'Un compte existe déjà avec cette adresse. Connecte-toi par « Lien par e-mail », puis choisis un mot de passe dans Réglages.':'An account already exists with this address. Sign in with “Email link”, then set a password in Settings.',
'Tu en as déjà un. Écris-en un nouveau pour le changer.':'You already have one. Type a new one to change it.','Choisis-en un pour te connecter sans attendre d’e-mail.':'Set one to sign in without waiting for an email.',
'Enregistrer':'Save','Astuce : choisis un mot de passe.':'Tip: set a password.','Tu pourras te connecter tout de suite, sans attendre d’e-mail.':'You’ll sign in straight away, without waiting for an email.',
'Choisir un mot de passe':'Set a password','Mot de passe enregistré. La prochaine fois, connecte-toi avec « Mot de passe ».':'Password saved. Next time, sign in with “Password”.',

/* --- mot de passe oublié --- */
'Afficher le mot de passe':'Show password','Masquer le mot de passe':'Hide password','Mot de passe oublié ?':'Forgot password?','Créer un compte':'Create an account',
'J’ai déjà un compte':'I already have an account','Un seul e-mail pour confirmer ton adresse, ensuite ton mot de passe suffit.':'A single email to confirm your address, then your password is enough.',
'Pratique si tu n’as pas encore de mot de passe. Tu pourras en choisir un ensuite dans Réglages.':'Handy if you don’t have a password yet. You can set one afterwards in Settings.',
'Mot de passe oublié':'Forgot password','Entre ton adresse : tu reçois un lien pour en choisir un nouveau. Ça marche aussi si tu n’en as jamais eu.':'Enter your address: you’ll get a link to choose a new one. It also works if you never had one.',
'Recevoir le lien':'Send me the link','Retour à la connexion':'Back to sign in','Retour':'Back',
'Un lien pour choisir ton nouveau mot de passe vient d’être envoyé à':'A link to choose your new password has just been sent to',
'Rien reçu après quelques minutes ? Regarde dans les spams.':'Nothing after a few minutes? Check your spam folder.',
'Choisis ton nouveau mot de passe':'Choose your new password','Pour le compte':'For the account','Nouveau mot de passe':'New password',
'Enregistrer et continuer':'Save and continue','Enregistrement…':'Saving…','Plus tard':'Later','Enregistrement impossible. Réessaie dans un instant.':'Couldn’t save. Try again in a moment.',

/* --- notifications --- */
'Notifications de bureau':'Desktop notifications','Activer les notifications':'Turn on notifications','Rappel des tâches du jour':'Reminder of today’s tasks',
'Activité sur les projets partagés':'Activity on shared projects','Quelles notifications':'Which notifications','Envoyer un test':'Send a test','Désactiver':'Turn off',
'Reçois un petit message sur ton écran pour les tâches du jour et quand quelqu’un avance sur un projet partagé.':'Get a small message on your screen for today’s tasks and when someone makes progress on a shared project.',
'Elles arrivent tant qu’On Stride est ouverte sur cet appareil, même dans un onglet en arrière-plan ou une fenêtre réduite. Quand tu regardes déjà l’appli, un petit message s’affiche en bas à la place.':'They arrive as long as On Stride is open on this device, even in a background tab or a minimised window. When you’re already looking at the app, a small message shows at the bottom instead.',
'Ce navigateur ne sait pas afficher de notifications. Sur iPhone : ajoute d’abord On Stride à l’écran d’accueil (bouton Partager, puis « Sur l’écran d’accueil »), ouvre-la depuis l’icône, puis reviens ici.':'This browser can’t show notifications. On iPhone: first add On Stride to your home screen (Share button, then “Add to Home Screen”), open it from the icon, then come back here.',
'Les notifications sont bloquées pour ce site. Pour les autoriser : clique sur le cadenas à gauche de l’adresse du site, mets « Notifications » sur « Autoriser », puis recharge la page.':'Notifications are blocked for this site. To allow them: click the padlock left of the site address, set “Notifications” to “Allow”, then reload the page.',
'Notifications activées sur cet appareil.':'Notifications turned on for this device.','Notifications désactivées sur cet appareil.':'Notifications turned off for this device.',
'Notifications bloquées par le navigateur.':'Notifications blocked by the browser.','Les notifications sont activées. Tu seras prévenu ici.':'Notifications are on. You’ll be alerted here.',
'Voici à quoi ressemble une notification.':'This is what a notification looks like.',
'Notification envoyée. Si rien n’apparaît, vérifie le mode « Ne pas déranger » de ton ordinateur.':'Notification sent. If nothing shows up, check your computer’s “Do not disturb” mode.',
'Impossible d’afficher la notification sur ce navigateur.':'Can’t show the notification in this browser.','Ta journée':'Your day',
'« {0} » est maintenant partagé avec toi.':'“{0}” is now shared with you.','Un projet est maintenant partagé avec toi.':'A project is now shared with you.','Nouveau projet partagé':'New shared project',
'{0} changements sur tes projets partagés':'{0} changes on your shared projects','Quelqu’un':'Someone','a commenté : « {0} »':'commented: “{0}”',

/* --- fichiers --- */
'Fichiers':'Files','Joindre un fichier':'Attach a file','PDF, devis, documents, archives… jusqu’à 25 Mo chacun.':'PDFs, quotes, documents, archives… up to 25 MB each.',
'Télécharger « {0} »':'Download “{0}”','Supprimer « {0} »':'Delete “{0}”','« {0} » supprimé.':'“{0}” deleted.','Envoi en cours…':'Uploading…',
'Maximum {0} fichiers par tâche.':'Maximum {0} files per task.','Maximum {0} fichiers par tâche : les suivants n’ont pas été ajoutés.':'Maximum {0} files per task: the rest weren’t added.',
'« {0} » est trop lourd (25 Mo maximum).':'“{0}” is too large (25 MB maximum).','{0} fichiers trop lourds (25 Mo maximum).':'{0} files too large (25 MB maximum).',
'Les fichiers ne sont pas encore activés : relance le fichier supabase/schema.sql dans Supabase.':'Files aren’t enabled yet: run the file supabase/schema.sql again in Supabase.',
'Envoi du fichier impossible. Réessaie dans un instant.':'Couldn’t upload the file. Try again in a moment.','Téléchargement impossible pour le moment.':'Can’t download right now.',
'Fichier ajouté':'File added','Fichiers ajoutés':'Files added',

/* --- formules --- */
'Formules':'Plans','Formule':'Plan','Gratuit':'Free','Premium':'Premium','Pro':'Pro','Admin':'Admin',
'Commence gratuitement, passe à la suite quand tu en as besoin.':'Start for free, move up when you need to.','Facturation':'Billing','Mensuel':'Monthly','Annuel':'Yearly','2 mois offerts':'2 months free',
'Pour toujours':'Forever','/ mois':'/ month','/ an':'/ year','soit {0} par mois':'that’s {0} a month','ou {0} par an':'or {0} a year','Le plus choisi':'Most popular',
'Projets illimités':'Unlimited projects','{0} projets actifs':'{0} active projects','{0} photos par tâche':'{0} photos per task','{0} fichiers par tâche, {1} chacun':'{0} files per task, {1} each',
'Couleurs en plus et badge':'Extra colours and a badge','Couleurs de base':'Standard colours','Export des tâches en tableur (Excel)':'Export tasks to a spreadsheet (Excel)','Aide prioritaire':'Priority help',
'Partage, tâches, calendrier, clients, notifications':'Sharing, tasks, calendar, clients, notifications','Ta formule actuelle':'Your current plan','Contacter pour {0}':'Contact me for {0}','Bientôt disponible':'Coming soon',
'Le paiement en ligne arrive bientôt. En attendant, envoie un message : ta formule est activée à la main, avec l’adresse e-mail de ton compte.':'Online payment is coming soon. Until then, send a message: your plan is switched on by hand, using your account’s email address.',
'au mois':'monthly','à l’année':'yearly','On Stride {0} ({1})':'On Stride {0} ({1})','Bonjour, je voudrais passer à la formule {0} ({1}) pour le compte {2}. Merci !':'Hello, I’d like to switch to the {0} plan ({1}) for the account {2}. Thanks!',
'Tu es admin : tout est débloqué.':'You’re an admin: everything is unlocked.','Tu as la formule {0} jusqu’au {1}.':'You have the {0} plan until {1}.','Tu as la formule {0}.':'You have the {0} plan.',
'Admin : tout est débloqué.':'Admin: everything is unlocked.','5 projets actifs, 3 photos et 3 fichiers par tâche.':'5 active projects, 3 photos and 3 files per task.','Jusqu’au {0}.':'Until {0}.','Sans date de fin.':'No end date.',
'Passer à Premium':'Upgrade to Premium','Voir les formules':'See the plans','Passe à Premium':'Upgrade to Premium','Exporter en tableur (Excel)':'Export to a spreadsheet (Excel)',
'Or':'Gold','Menthe':'Mint','Lavande':'Lavender','Framboise':'Raspberry','Nuit':'Night',
'Tu as atteint 5 projets actifs, la limite de la formule Gratuite. Archive un projet, ou passe à Premium pour en avoir autant que tu veux.':'You’ve reached 5 active projects, the limit of the Free plan. Archive a project, or upgrade to Premium to have as many as you like.',
'La formule Gratuite permet 3 photos par tâche. Premium en permet 8.':'The Free plan allows 3 photos per task. Premium allows 8.',
'La formule Gratuite permet 3 fichiers de 5 Mo par tâche. Premium : 10 fichiers de 25 Mo, Pro : 50 Mo.':'The Free plan allows 3 files of 5 MB per task. Premium: 10 files of 25 MB, Pro: 50 MB.',
'Ce fichier dépasse la taille permise par ta formule.':'This file is larger than your plan allows.','Ces couleurs sont réservées aux formules Premium et Pro.':'These colours are for the Premium and Pro plans.',
'L’export en tableur fait partie de la formule Pro.':'Spreadsheet export is part of the Pro plan.','Plus de photos avec Premium':'More photos with Premium','Plus de fichiers avec Premium':'More files with Premium',
'PDF, devis, documents, archives… jusqu’à {0} chacun.':'PDFs, quotes, documents, archives… up to {0} each.','« {0} » est trop lourd ({1} maximum).':'“{0}” is too large ({1} maximum).','{0} fichiers trop lourds ({1} maximum).':'{0} files too large ({1} maximum).',
'Choisis qui a Premium ou Pro. Visible par toi seul.':'Choose who gets Premium or Pro. Only you can see this.','Premium actifs':'Active Premium','Pro actifs':'Active Pro','Expirés':'Expired','Expiré':'Expired',
'Donner une formule':'Give a plan','Durée':'Duration','Activer':'Activate','1 mois':'1 month','1 an':'1 year','Sans fin (offert)':'No end (free gift)','+1 mois':'+1 month','+1 an':'+1 year',
'La personne doit se connecter avec cette adresse. Si elle a déjà une formule en cours, la durée s’ajoute à ce qui reste.':'The person must sign in with this address. If they already have a plan running, the duration is added to what’s left.',
'Comptes avec une formule':'Accounts with a plan','Chercher une adresse':'Search an address','Personne pour l’instant':'Nobody yet','Ajoute une adresse e-mail ci-dessus pour donner Premium ou Pro.':'Add an email address above to give Premium or Pro.',
'Aucune adresse ne correspond.':'No matching address.','jusqu’au {0}':'until {0}','expiré le {0}':'expired on {0}','sans fin':'no end','par {0}':'by {0}','Prolonger de {0}':'Extend by {0}','Retirer la formule de {0}':'Remove {0}’s plan',
'{0} : prolongé.':'{0}: extended.','{0} a maintenant la formule {1}.':'{0} now has the {1} plan.','{0} repasse en formule Gratuite.':'{0} is back on the Free plan.','Suppression impossible. Réessaie dans un instant.':'Couldn’t remove. Try again in a moment.',
'La table des formules n’existe pas encore : relance le fichier supabase/schema.sql dans Supabase (SQL Editor), puis recharge la page.':'The plans table doesn’t exist yet: run the file supabase/schema.sql again in Supabase (SQL Editor), then reload the page.',
'Oui':'Yes','Non':'No',

/* --- messages --- */
'Modification refusée : tu n’as pas les droits sur cet élément.':'Change refused: you don’t have permission for this item.',
'Enregistrement impossible. Réessaie dans un instant.':'Couldn’t save. Try again in a moment.',
'Tâche ajoutée à « {q} ».':'Task added to “{q}”.','Tâche ajoutée à l’Inbox.':'Task added to the Inbox.','Rangée dans « {q} ».':'Filed into “{q}”.','Déplacée dans « {q} ».':'Moved to “{q}”.',
'Carte supprimée.':'Card deleted.','Carte dupliquée.':'Card duplicated.','Lien copié.':'Link copied.',
'Projet privé : tes invités ne le voient plus.':'Private project: your guests can no longer see it.','Projet partagé : tes invités peuvent le voir.':'Shared project: your guests can see it.',
'Export téléchargé.':'Export downloaded.','Export impossible pour le moment.':'Can’t export right now.','Adresse e-mail invalide.':'Invalid email address.',
'C’est ton adresse : tu es déjà propriétaire.':'That’s your address: you’re already the owner.','Cette personne a déjà accès.':'This person already has access.',
'{0} peut maintenant modifier ce projet.':'{0} can now edit this project.','{0} peut maintenant voir ce projet.':'{0} can now view this project.','{0} n’a plus accès.':'{0} no longer has access.',
'Ce projet n’existe pas, ou il n’est pas partagé avec ton adresse ({0}).':'This project doesn’t exist, or it isn’t shared with your address ({0}).',
'Connecte-toi à Claude':'Sign in','Il faut être connecté pour voir l’avancée de ces projets.':'You need to be signed in to see these projects.',
'La base de données n’est pas encore initialisée : exécute le fichier supabase/schema.sql dans Supabase (SQL Editor), puis recharge la page.':'The database isn’t set up yet: run the file supabase/schema.sql in Supabase (SQL Editor), then reload the page.',
'Les données ne se chargent pas correctement (':'The data isn’t loading properly (','). Recharge la page.':'). Reload the page.',
'(copie)':'(copy)',

/* --- historique des cartes (enregistré en français, traduit à l'affichage) --- */
'Carte créée':'Card created','Rangée dans « {q} »':'Filed into “{q}”','Déplacée vers « {q} »':'Moved to “{q}”','Marquée comme terminée':'Marked as done','Rouverte':'Reopened',
'Carte dupliquée':'Card duplicated','Checklist terminée':'Checklist completed','Échéance retirée':'Due date removed','Plus assignée':'Unassigned','Commentaire ajouté':'Comment added',
'Priorité : aucune':'Priority: none','Priorité : basse':'Priority: low','Priorité : moyenne':'Priority: medium','Priorité : haute':'Priority: high'
},[
  [/^Total : (.+) · encaissé (.+) · reste (.+)$/,'Total: $1 · received $2 · outstanding $3'],
  [/^reste (.+)$/,'$1 outstanding'],
  [/^encaissé (.+)$/,'received $1'],
  [/^Début : (.+)$/,'Start: $1'],
  [/^Échéance : (.+)$/,'Due date: $1'],
  [/^Assignée à (.+)$/,'Assigned to $1'],
  [/^Icône (.+)$/,'Icon $1'],
  [/^(\d{1,2} [A-Za-zéû]{3,9}\.?)$/,'$1']
]);

/* --- tableau blanc, chrono, point client --- */
I18N.add('en',{
'Tableau blanc':'Whiteboard','Vue Tableau blanc':'Whiteboard view','Bloc':'Block','Carte':'Card','Relier ce bloc à un autre':'Link this block to another','Tire vers un autre bloc pour les relier':'Drag to another block to link them',
'Carte supprimée':'Card deleted','Titre de la carte':'Card title','Titre du bloc':'Block title','Texte du bloc':'Block text','Titre':'Title','Écris une idée, une étape, une question…':'Write an idea, a step, a question…',
'En attente de « {0} »':'Waiting for “{0}”','En attente de « {0} » et {1} de plus':'Waiting for “{0}” and {1} more','Ouvrir la carte':'Open card','Poser une carte…':'Place a card…','−15 min':'−15 min','+15 min':'+15 min','Poser une carte existante':'Place an existing card',
'Sans titre':'Untitled','Couleur du bloc':'Block colour','Transformer ce bloc en carte du Kanban':'Turn this block into a Kanban card','En faire une carte':'Make it a card','Retirer le bloc':'Remove block','Supprimer le lien':'Delete link',
'Dézoomer':'Zoom out','Zoomer':'Zoom in','Recentrer':'Fit to view','Un tableau blanc pour y voir clair':'A whiteboard to see things clearly',
'Double-clique dans le vide pour poser un bloc. Tire depuis le point à droite d’un bloc pour le relier à un autre. Pose aussi tes cartes : un lien entre deux cartes indique laquelle doit être finie d’abord.':'Double-click an empty spot to add a block. Drag from the dot on the right of a block to link it to another. Place your cards too: a link between two cards shows which one has to be finished first.',
'Ce projet n’a pas encore de tableau blanc.':'This project has no whiteboard yet.',
'Double-clic : nouveau bloc · Glisser le fond : se déplacer · Molette : zoom · Suppr : effacer la sélection':'Double-click: new block · Drag the background: move around · Wheel: zoom · Del: delete selection',
'Bloc retiré du tableau blanc.':'Block removed from the whiteboard.','Lien supprimé.':'Link deleted.','Nouvelle carte':'New card','Carte créée dans « {q} ».':'Card created in “{q}”.',
'Temps passé':'Time spent','Visible par toi seul':'Only visible to you','Arrêter':'Stop','Démarrer':'Start','Retirer 15 minutes':'Remove 15 minutes','Ajouter 15 minutes':'Add 15 minutes','Taux horaire réel':'Actual hourly rate',
'Arrêter le chrono':'Stop the timer','Chrono resté ouvert longtemps : compté 12 h au maximum. Ajuste si besoin.':'The timer was left running for a long time: counted 12 h at most. Adjust if needed.',
'Point client':'Client update','Préparer un message d’avancement pour ton client':'Prepare a progress message for your client','Message':'Message',
'Dernier point envoyé {0}. Ce message reprend ce qui a bougé depuis.':'Last update sent {0}. This message covers what has moved since.',
'Un message écrit à partir de tes cartes. Relis-le, ajuste-le, puis envoie-le.':'A message written from your cards. Read it over, adjust it, then send it.',
'Ouvrir dans ma messagerie':'Open in my mail app','Ajoute l’e-mail du client dans sa fiche pour l’envoyer en un clic.':'Add the client’s email to their record to send it in one click.','Copier':'Copy',
'Point copié. Colle-le dans ton e-mail ou ta messagerie.':'Update copied. Paste it into your email or chat.','Copie impossible : sélectionne le texte et copie-le à la main.':'Could not copy: select the text and copy it by hand.',
'Point d’avancement : {0}':'Progress update: {0}','Bonjour {0},':'Hello {0},','Bonjour,':'Hello,',
'Voici où en est « {0} » : {1} % terminé ({2} sur {3}).':'Here is where “{0}” stands: {1}% done ({2} of {3}).','Échéance prévue : {0}.':'Planned deadline: {0}.',
'Terminé depuis le dernier point :':'Done since the last update:','Terminé ces deux dernières semaines :':'Done over the last two weeks:','En cours :':'In progress:','Prochaines étapes :':'Next steps:',
'À noter : {0} points ont pris du retard, je m’en occupe en priorité.':'Please note: {0} items are running late, I am dealing with them first.','À noter : un point a pris du retard, je m’en occupe en priorité.':'Please note: one item is running late, I am dealing with it first.',
'Rien de nouveau à signaler pour le moment.':'Nothing new to report for now.','N’hésite pas si tu as des questions.':'Let me know if you have any questions.','Bonne journée,':'Have a good day,'
});

/* --- mode focus, relances de paiement, cartes récurrentes --- */
I18N.add('en',{
'Focus':'Focus','Focus : quoi faire maintenant':'Focus: what to do now','Une seule tâche à l’écran : la plus utile à faire maintenant':'One task on screen: the most useful one to do now',
'En retard de {0} jours':'{0} days late','En retard depuis hier':'Late since yesterday','À rendre aujourd’hui':'Due today','À rendre le {0}':'Due on {0}','Priorité haute':'High priority',
'Déjà commencée : autant la finir':'Already started: might as well finish it','La plus ancienne de ta liste':'The oldest on your list',
'Plus rien à proposer':'Nothing left to suggest','Rien à faire pour l’instant':'Nothing to do right now','Tu as passé toutes les tâches restantes.':'You skipped all the remaining tasks.','Aucune tâche ouverte ne t’attend. Profites-en.':'No open task is waiting for you. Enjoy it.',
'Revoir les tâches passées':'Go back to skipped tasks','C’est fait':'Done','Je m’y mets':'Start working','Arrêter le chrono':'Stop the timer','Ouvrir':'Open','Passer':'Skip',
'Encore {0} tâches après celle-ci.':'{0} more tasks after this one.','Encore une tâche après celle-ci.':'One more task after this one.','C’est la dernière de ta liste.':'This is the last one on your list.',
'À encaisser':'To collect','Rien à encaisser':'Nothing to collect','Renseigne le montant et l’encaissé d’un projet pour suivre ce qu’on te doit.':'Fill in a project’s amount and what you received to track what you are owed.',
'Relancer':'Remind','Le projet n’est pas encore livré':'The project is not delivered yet','En cours':'In progress','relancé {0} ·':'reminded {0} ·',
'{0} projets livrés attendent un règlement.':'{0} delivered projects are awaiting payment.','Un projet livré attend un règlement.':'One delivered project is awaiting payment.','Total à encaisser :':'Total to collect:',
'Relancer le paiement':'Send a payment reminder','Dernière relance {0}':'Last reminder {0}','Dernière relance {0}.':'Last reminder {0}.','Relance de paiement':'Payment reminder',
'Un message poli à partir du montant et de l’encaissé du projet. Relis-le avant de l’envoyer.':'A polite message based on the project’s amount and what you received. Read it over before sending.',
'Je me permets de revenir vers toi au sujet du règlement de « {0} ».':'I am following up again about the payment for “{0}”.','J’espère que tu vas bien. Je reviens vers toi au sujet du règlement de « {0} ».':'I hope you are well. I am getting in touch about the payment for “{0}”.',
'Sauf erreur de ma part, il reste {0} à régler sur un total de {1} (déjà reçu : {2}).':'Unless I am mistaken, {0} is still outstanding out of a total of {1} (already received: {2}).','Sauf erreur de ma part, le montant de {0} n’a pas encore été réglé.':'Unless I am mistaken, the amount of {0} has not been paid yet.',
'Peux-tu me dire quand le règlement est prévu ? Je te renvoie la facture si besoin.':'Could you let me know when payment is planned? I can send the invoice again if needed.','Merci d’avance,':'Thanks in advance,',
'Règlement : {0}':'Payment: {0}','Relance copiée. Colle-la dans ton e-mail ou ta messagerie.':'Reminder copied. Paste it into your email or chat.',
'Jamais':'Never','Chaque jour':'Every day','Chaque semaine':'Every week','Chaque mois':'Every month','Répéter':'Repeat','Carte récurrente':'Recurring card','Carte récurrente créée':'Recurring card created',
'Carte récurrente : la suivante est prévue le {0}.':'Recurring card: the next one is due on {0}.','Ajoute une échéance : la prochaine carte partira de cette date.':'Add a due date: the next card will start from that date.',
'Répétition : chaque jour':'Repeat: every day','Répétition : chaque semaine':'Repeat: every week','Répétition : chaque mois':'Repeat: every month','Répétition retirée':'Repeat removed'
});
